### ISSUE TITLE
Fast Refresh is disabled in your application due to an outdated `react` version

### ISSUE THREAD

**Issue by muuvmuuv** [preactjs/next-plugin-preact#21]
```
warn  - Fast Refresh is disabled in your application due to an outdated `react` version. Please upgrade 16.10 or newer! Read more: https://err.sh/next.js/react-version
```

Can this be ignored?

**Comment by meck93** [comment]
Hi @muuvmuuv 

I think it can be safely ignored since Fast Refresh is React specific. Preact uses [Prefresh ](https://github.com/JoviDeCroock/prefresh) and is included in this package as you can see here: https://github.com/preactjs/next-plugin-preact/blob/a1819d208a881ca25574b2c410e9129f9139c91d/packages/next-plugin-preact/index.js#L13

Prefresh works like Fast Refresh for me. I ignored this warning message. Plus, with `Next.JS 10.0.6` the warning no longer appears for me.
